CREATE TABLE PUBLIC.T_USER(
    ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);            
ALTER TABLE PUBLIC.T_USER ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);

CREATE TABLE PUBLIC.T_CAR(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    YEAR VARCHAR(255),
    USER_ID BIGINT,
    BRAND_ID BIGINT,
);            
ALTER TABLE PUBLIC.T_CAR ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);

CREATE TABLE PUBLIC.T_BRAND(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255)
);            
ALTER TABLE PUBLIC.T_BRAND ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);

CREATE SEQUENCE PUBLIC.SARJ_SEQUENCE START WITH 100;
